-- 自動產生：node scripts/generate-seed.mjs（請勿手改，改 JSON 後重新產生）
begin;
insert into checklist_sections (name, sort_order) values ('人員', 1) on conflict do nothing;
insert into checklist_sections (name, sort_order) values ('清潔、準清潔區', 2) on conflict do nothing;
insert into checklist_sections (name, sort_order) values ('環境', 3) on conflict do nothing;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 2, '穿戴整潔之工作衣帽、髮帽、口罩、雨鞋或鞋套。', false, 1 from checklist_sections where name = '人員' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 3, '依清潔、準清潔及一般區域分顏色戴帽子。', false, 2 from checklist_sections where name = '人員' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 4, '保持手部清潔，不得蓄留指甲、塗指甲油及佩帶飾物，必要時戴手套。', false, 3 from checklist_sections where name = '人員' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 5, '接觸食品者不得有感冒、呼吸道症狀、皮膚病或手部有膿瘡、傷口等。', false, 4 from checklist_sections where name = '人員' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 6, '飲食與吸菸行為需到指定場所。', false, 5 from checklist_sections where name = '人員' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 7, '私人物品應放置於置物櫃，不可任意擺置。', false, 6 from checklist_sections where name = '人員' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 8, '門在無使用時緊閉。', false, 1 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 9, '窗戶在無使用時緊閉，如有開啟均有紗窗，紗窗有緊閉無隙縫。', false, 2 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 10, '進入時走浴塵室，用清潔劑洗手並用酒精與泡鞋池消毒，清潔與消毒設備皆正常。', false, 3 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 11, '水溝應排水功能完善，保持乾淨暢通，無雜物阻塞。', false, 4 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 12, '不得有紙箱與竹、木製器具。', false, 5 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 13, '不得有病媒侵入。', false, 6 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 14, '不得堆積與加工無關之雜物。', false, 7 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 15, '餘料有防護並有明顯標示。', false, 8 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 16, '工器具於未使用的情況時均有擺放於固定位置。', false, 9 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 17, '食品與調理器具擺放於棧板上，不得直接接觸地面。', false, 10 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 18, '地面應無破損、積水、髒汙之現象。', false, 11 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 19, '設備、工作台及器具應完好、清潔。', false, 12 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 20, '易碎物應保持完整，不得有龜裂或破損。', false, 13 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 21, '製程不良品及退貨品不可任意堆放。', false, 14 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 22, '如原、配料有過敏原成分應使用專用棧板並有明確標示與區隔。', false, 15 from checklist_sections where name = '清潔、準清潔區' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 23, '牆壁、天花板保持清潔、無破損、蜘蛛網等。', false, 1 from checklist_sections where name = '環境' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 24, '走道應保持整潔且暢通。', false, 2 from checklist_sections where name = '環境' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 25, '垃圾與廢料應於當日拋棄並分類置於規定場所，不得在現場留過夜。', false, 3 from checklist_sections where name = '環境' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 26, '廚餘桶蓋子有蓋好，桶身保持乾淨。', false, 4 from checklist_sections where name = '環境' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 27, '廁所功能正常，並保持清潔衛生。', false, 5 from checklist_sections where name = '環境' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 28, '更衣室、置物櫃內應保持清潔衛生，不得放置食品。', false, 6 from checklist_sections where name = '環境' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 29, '化學品及其專櫃之維護: 標示完整，且分裝日期及有效日期皆在效期內。', false, 7 from checklist_sections where name = '環境' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into checklist_items (section_id, item_no, content, has_temp_facility_field, sort_order) select id, 30, '■無□有暫時性設施＿＿＿＿＿不可造成污染及滋生蟲害。', true, 8 from checklist_sections where name = '環境' on conflict (item_no) do update set content = excluded.content, sort_order = excluded.sort_order;
insert into responsible_units (name, sort_order) values ('原料班', 1) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('果醬調理班', 2) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('果餡調理班', 3) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('果醬(餡)充填班', 4) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('花生班', 5) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('包裝班', 6) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('資材', 7) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('工務課', 8) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('工務-廢水場', 9) on conflict (name) do nothing;
insert into responsible_units (name, sort_order) values ('配料室', 10) on conflict (name) do nothing;
insert into inspectors (name, sort_order) values ('林俊廷', 1) on conflict (name) do nothing;
insert into inspectors (name, sort_order) values ('王品儒', 2) on conflict (name) do nothing;
insert into inspectors (name, sort_order) values ('李育儒', 3) on conflict (name) do nothing;
insert into app_settings (key, value) values ('qa_sla_working_days', '5'::jsonb) on conflict (key) do update set value = excluded.value, updated_at = now();
insert into app_settings (key, value) values ('due_soon_working_days', '2'::jsonb) on conflict (key) do update set value = excluded.value, updated_at = now();
insert into holidays (holiday_date, name) values ('2026-01-01', '元旦') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-02-14', '農曆除夕前補假') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-02-16', '農曆除夕') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-02-17', '春節初一') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-02-18', '春節初二') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-02-19', '春節初三') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-02-20', '春節補假') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-02-27', '和平紀念日補假') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-04-03', '兒童節補假') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-04-06', '清明節補假') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-05-01', '勞動節') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-06-19', '端午節') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-09-25', '中秋節') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-09-28', '教師節') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-10-09', '國慶日補假') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-10-26', '光復節補假') on conflict do nothing;
insert into holidays (holiday_date, name) values ('2026-12-25', '行憲紀念日') on conflict do nothing;
commit;
